Algoritmo "contador"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson costa
// Descrição   :exemplo laço de repetição for
// Autor(a)    : Carlos Bonfim
// Data atual  : 04/04/2024
Var
// Seção de Declarações das variáveis 

contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  para contador de 1 ate 10 passo 1 faca
  escreval(contador)
  fimpara

Fimalgoritmo