Algoritmo "manzano66_exer_a"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson costa
// Descrição   :fazer a potência de 15 a 200 usando ciclo for
// Autor(a)    : Carlos Bonfim
// Data atual  : 04/04/2024
Var
   // Seção de Declarações das variáveis
     contador:inteiro;
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
       para contador de 15 ate 200 faca
       escreval(contador ^ 2)
       fimpara
Fimalgoritmo