Algoritmo "manzano66_exer_g"
// Disciplina   : [ Lógica de Programação com javascript]
// Professor   : Jailson dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Carlos Oliveira Bonfim
// Data atual  : 04/04/2024
Var
// Seção de Declarações das variáveis 

     contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       para contador de 0 ate 15 faca
            escreval(3 ^ contador)
        fimpara

Fimalgoritmo