Algoritmo "manzano50_exer_c"
// Disciplina   : [ Lógica de Programação com javascript]
// Professor   : Jailson dos Santos 
// Descrição   :
// Autor(a)    : Carlos Oliveira Bonfim
// Data atual  : 06/04/2024
Var
// Seção de Declarações das variáveis 

  contador:inteiro;
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   repita
   se contador % 4 = 0 entao
   escreval(contador)
   fimse
   contador <- contador + 1
   ate contador > 200

Fimalgoritmo